apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sashiko-ingress
  namespace: sashiko
spec:
  defaultBackend:
    service:
      name: sashiko-maintenance-service
      port:
        number: 80
