# Copyright 2026 The Sashiko Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Build one synthetic Git commit pair per source group."""

import os
from pathlib import Path

from .io import git, run


def initialize_repository(repo_dir):
    repo_dir = Path(repo_dir)
    git(repo_dir, "init")
    git(repo_dir, "config", "user.name", "codebase-scan")
    git(repo_dir, "config", "user.email", "scan@localhost")
    git(repo_dir, "add", "-A")
    git(repo_dir, "commit", "-m", "snapshot: full source tree")
    return git(repo_dir, "rev-parse", "HEAD")


def commit_tree(repo_dir, treeish, message, parents=None, index_path=None, remove=None):
    environment = os.environ.copy()
    if index_path:
        environment["GIT_INDEX_FILE"] = str(index_path)
    if remove:
        run(["git", "read-tree", treeish], cwd=repo_dir, env=environment)
        run(
            ["git", "update-index", "--force-remove", "--"] + list(remove),
            cwd=repo_dir,
            env=environment,
        )
        treeish = run(
            ["git", "write-tree"], cwd=repo_dir, env=environment
        )[1].strip()
    command = ["git", "commit-tree", treeish]
    for parent in parents or []:
        command.extend(["-p", parent])
    return run(
        command, cwd=repo_dir, env=environment, input_text=message
    )[1].strip()


def baseline_blob(repo_dir, regions):
    content = (Path(repo_dir) / regions[0]["path"]).read_bytes()
    lines = content.splitlines(keepends=True)
    removed = removed_line_indexes(regions)
    baseline = b"".join(
        line for index, line in enumerate(lines) if index not in removed
    )
    return run(
        ["git", "hash-object", "-w", "--stdin"],
        cwd=repo_dir,
        input_text=baseline,
    )[1].strip()


def removed_line_indexes(regions):
    removed = set()
    for region in regions:
        removed.update(range(region["start_line"] - 1, region["end_line"]))
    return removed


def temporary_index_path(output_dir, index):
    return Path(output_dir) / ".indexes" / ("%06d.index" % index)


def remove_temporary_index(index_path):
    for path in (Path(index_path), Path(str(index_path) + ".lock")):
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def baseline_commit(repo_dir, output_dir, full_commit, group, index):
    index_path = temporary_index_path(output_dir, index)
    index_path.parent.mkdir(parents=True, exist_ok=True)
    environment = os.environ.copy()
    environment["GIT_INDEX_FILE"] = str(index_path)
    run(["git", "read-tree", full_commit], cwd=repo_dir, env=environment)
    regions_by_path = {}
    for region in group["target_regions"]:
        regions_by_path.setdefault(region["path"], []).append(region)
    for path, regions in sorted(regions_by_path.items()):
        mode = git(repo_dir, "ls-tree", full_commit, "--", path).split()[0]
        blob = baseline_blob(repo_dir, regions)
        line_count = len(
            (Path(repo_dir) / path).read_bytes().splitlines(keepends=True)
        )
        if removed_line_indexes(regions).issuperset(range(line_count)):
            run(
                ["git", "update-index", "--force-remove", "--", path],
                cwd=repo_dir,
                env=environment,
            )
        else:
            run(
                ["git", "update-index", "--cacheinfo", mode, blob, path],
                cwd=repo_dir,
                env=environment,
            )
    tree = run(["git", "write-tree"], cwd=repo_dir, env=environment)[1].strip()
    return commit_tree(
        repo_dir,
        tree,
        "snapshot baseline without %s\n" % group["group_id"],
    )


def build_patch(repo_dir, output_dir, full_commit, full_tree, group, index):
    repo_dir = Path(repo_dir)
    index_path = temporary_index_path(output_dir, index)
    try:
        baseline = baseline_commit(
            repo_dir, output_dir, full_commit, group, index
        )
        target = commit_tree(
            repo_dir,
            full_tree,
            (
                "snapshot: add %s\n\n"
                "Synthetic source-tree PatchInput generated by codebase-scan.\n"
            )
            % group["group_id"],
            parents=[baseline],
        )
        diff = git(
            repo_dir,
            "show",
            "--format=fuller",
            "--no-ext-diff",
            target,
        )
    finally:
        remove_temporary_index(index_path)
    return {
        "index": index,
        "group_id": group["group_id"],
        "target_files": group["files"],
        "target_regions": group["target_regions"],
        "priority_rank": group["priority_rank"],
        "score": group["score"],
        "lines": group["lines"],
        "bytes": group["bytes"],
        "baseline_commit": baseline,
        "target_commit": target,
        "subject": "snapshot: add %s" % group["group_id"],
        "diff": diff,
    }


def build_patches(repo_dir, output_dir, full_commit, groups):
    repo_dir = Path(repo_dir)
    full_tree = git(repo_dir, "rev-parse", "%s^{tree}" % full_commit)
    patches = []
    for index, group in enumerate(groups, 1):
        patches.append(build_patch(repo_dir, output_dir, full_commit, full_tree, group, index))
    return patches


def public_patch(patch):
    return {key: value for key, value in patch.items() if key != "diff"}


def review_input(project, patch):
    return {
        "id": 0,
        "subject": "Repository snapshot review: %s" % project,
        "patches": [
            {
                "index": 1,
                "diff": patch["diff"],
                "subject": patch["subject"],
                "author": "codebase-scan <scan@localhost>",
                "date": 0,
                "message_id": None,
                "commit_id": patch["target_commit"],
            }
        ],
    }
