apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sashiko-gcc-ingress.yaml
  - sashiko-gcc-backendconfig.yaml
  - sashiko-gcc-service-skeleton.yaml
  - maintenance-setup.yaml
  - managed-certificate.yaml
