name: Pull Request Workflow
on:
  pull_request:
    branches: [main]

jobs:
  check-sob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Check Developer Certificate of Origin (S-O-B)
        run: |
          TARGET_BRANCH=${GITHUB_BASE_REF:-main}
          make sob RANGE="origin/$TARGET_BRANCH..HEAD"
  lint:
    needs: [check-sob]
    uses: ./.github/workflows/linting.yml
  run-tests:
    needs: [check-sob]
    uses: ./.github/workflows/unit-tests.yml
